japan/config/routes.rb
Rails.application.routes.draw do
  get 'tag/show'

  get 'static_pages/home'

  get 'static_pages/tips'

  get 'search', to: 'search#search'

  resources :attractions

  resources :categories

  resources :regions

  resources :attractions do
    collection { get :search }
  end

  resources :tag

end

japan/app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  acts_as_taggable


end

japan/app/controllers/static_pages_controller.rb
#require 'common_stuff'

class StaticPagesController < ApplicationController

  #include CommonStuff

  def home
  end

  def tips
  end

end

japan/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

japan/app/views/static_pages/home.html.erb
<h1>Strona domowa</h1>

<thead>
<meta charset='utf-8'>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="application.css">
<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<script src="script.js"></script>
<link rel="stylesheet" href="social-likes_flat.css">
</thead>

<tbody>
<div id='cssmenu'>
  <ul>
    <li class='active'><%= link_to "Home", static_pages_home_path %></li>
    <li><%= link_to "Wycieczki po fabrykach", regions_path %></li>
    <li><%= link_to "Targi technologiczne", regions_path %></li>
    <li><%= link_to "Muzea techniczne", regions_path %></li>
    <li><%= link_to "Wskazówki dla podróżnych", static_pages_tips_path %></li>
    <li class='last'><%= link_to"Wyszukiwarka atrakcji", regions_path %></li>
  </ul>
</div>

<h1>Nagłówek</h1>
<div>
  <%= image_tag("300.gif", :alt => "placeholder") %>
</div>
<div>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed interdum sapien. Lorem ipsum dolor sit amet,
    consectetur adipiscing elit. Curabitur consequat, leo in sodales sollicitudin, sem eros pellentesque diam, sit amet
    imperdiet est velit eu tellus. Curabitur neque eros, bibendum a augue eget, luctus accumsan turpis. Vivamus
    suscipit,  felis sit amet venenatis accumsan, urna purus vestibulum purus, ac porta sapien turpis at massa.
    Phasellus  ante purus, fringilla in justo quis, convallis commodo felis. Sed vel ex id lorem egestas faucibus eget
    vitae lorem. Integer faucibus ullamcorper dui, sit amet viverra sapien sodales vel. Nulla ante nibh, vulputate a
    gravida vel, semper vel nisi. Nam quis ligula vulputate, elementum libero eu, feugiat massa. Pellentesque habitant
    morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam in tincidunt enim, non euismod dui.
  </p>
  <%= button_to "Znajdź atrakcję", regions_path, :class => "button", :method => :get  %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="social-likes.min.js"></script>

  <div class="social-likes">
    <div class="facebook" title="Share link on Facebook">Facebook</div>
    <div class="twitter" title="Share link on Twitter">Twitter</div>
    <div class="plusone" title="Share link on Google+">Google+</div>
  </div>
</div>





</tbody>

japan/app/views/static_pages/tips.html.erb
<p id="notice"><%= notice %></p>
<h1>Wskazówki dla podróżnych</h1>


<thead>
  <meta charset='utf-8'>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="application.css">
  <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
  <script src="script.js"></script>

</thead>

<tbody>

<div id="cssmenu">
  <ul>
    <li><%= link_to "Home", static_pages_home_path %> </li>
    <li><%= link_to "Wycieczki po fabrykach", regions_path %></li>
    <li><%= link_to "Targi technologiczne", regions_path %></li>
    <li><%= link_to "Muzea techniczne", regions_path %></li>
    <li class='active'><%= link_to "Wskazówki dla podróżnych", static_pages_tips_path %></li>
    <li class='last'><%= link_to "Wyszukiwarka atrakcji", regions_path %></li>
  </ul>
</div>

<div id="tipsmenu">
  <ul>
    <li><a href="#paszport" class="smoothScroll"><span>Paszport</span></a></li>
    <li><a href="#waluta" class="smoothScroll"><span>Waluta</span></a></li>
    <li><a href="#waluta1" class="smoothScroll"><span>Waluta</span></a></li>
    <li><a href="#waluta2" class="smoothScroll"><span>Waluta</span></a></li>
    <li><a href="#waluta3" class="smoothScroll"><span>Waluta</span></a></li>
    <li><a href="#waluta4" class="smoothScroll"><span>Waluta</span></a></li>
  </ul>
</div>
<div>
  <strong><a name="paszport" id="paszport">Paszport</a> </strong>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed interdum sapien. Lorem ipsum dolor sit
   amet, consectetur adipiscing elit. Curabitur consequat, leo in sodales sollicitudin, sem eros pellentesque diam,
    sit amet imperdiet est velit eu tellus. Curabitur neque eros, bibendum a augue eget, luctus accumsan turpis.
    Vivamus suscipit, felis sit amet venenatis accumsan, urna purus vestibulum purus, ac porta sapien turpis at massa
    . Phasellus ante purus, fringilla in justo quis, convallis commodo felis. Sed vel ex id lorem egestas faucibus
    eget vitae lorem. Integer faucibus ullamcorper dui, sit amet viverra sapien sodales vel. Nulla ante nibh,
    vulputate a gravida vel, semper vel nisi. Nam quis ligula vulputate, elementum libero eu, feugiat massa.
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam in tincidunt
    enim, non euismod dui.
  </p>
  <a id="toTop" href="#">Go to Top</a>
</div>
<div>
  <strong><a name="waluta">Waluta</a> </strong>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed interdum sapien. Lorem ipsum dolor sit
    amet, consectetur adipiscing elit. Curabitur consequat, leo in sodales sollicitudin, sem eros pellentesque diam,
    sit amet imperdiet est velit eu tellus. Curabitur neque eros, bibendum a augue eget, luctus accumsan turpis.
    Vivamus suscipit, felis sit amet venenatis accumsan, urna purus vestibulum purus, ac porta sapien turpis at massa
    . Phasellus ante purus, fringilla in justo quis, convallis commodo felis. Sed vel ex id lorem egestas faucibus
    eget vitae lorem. Integer faucibus ullamcorper dui, sit amet viverra sapien sodales vel. Nulla ante nibh,
    vulputate a gravida vel, semper vel nisi. Nam quis ligula vulputate, elementum libero eu, feugiat massa.
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam in tincidunt
    enim, non euismod dui.
  </p>
</div>
<div>
  <strong><a name="waluta1">Waluta1</a> </strong>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed interdum sapien. Lorem ipsum dolor sit
    amet, consectetur adipiscing elit. Curabitur consequat, leo in sodales sollicitudin, sem eros pellentesque diam,
    sit amet imperdiet est velit eu tellus. Curabitur neque eros, bibendum a augue eget, luctus accumsan turpis.
    Vivamus suscipit, felis sit amet venenatis accumsan, urna purus vestibulum purus, ac porta sapien turpis at massa
    . Phasellus ante purus, fringilla in justo quis, convallis commodo felis. Sed vel ex id lorem egestas faucibus
    eget vitae lorem. Integer faucibus ullamcorper dui, sit amet viverra sapien sodales vel. Nulla ante nibh,
    vulputate a gravida vel, semper vel nisi. Nam quis ligula vulputate, elementum libero eu, feugiat massa.
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam in tincidunt
    enim, non euismod dui.
  </p>
</div>
<div>
  <strong><a name="waluta2">waluta2</a> </strong>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed interdum sapien. Lorem ipsum dolor sit
    amet, consectetur adipiscing elit. Curabitur consequat, leo in sodales sollicitudin, sem eros pellentesque diam,
    sit amet imperdiet est velit eu tellus. Curabitur neque eros, bibendum a augue eget, luctus accumsan turpis.
    Vivamus suscipit, felis sit amet venenatis accumsan, urna purus vestibulum purus, ac porta sapien turpis at massa
    . Phasellus ante purus, fringilla in justo quis, convallis commodo felis. Sed vel ex id lorem egestas faucibus
    eget vitae lorem. Integer faucibus ullamcorper dui, sit amet viverra sapien sodales vel. Nulla ante nibh,
    vulputate a gravida vel, semper vel nisi. Nam quis ligula vulputate, elementum libero eu, feugiat massa.
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam in tincidunt
    enim, non euismod dui.
  </p>
</div>
<div>
  <strong><a name="waluta3">waluta3</a> </strong>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed interdum sapien. Lorem ipsum dolor sit
    amet, consectetur adipiscing elit. Curabitur consequat, leo in sodales sollicitudin, sem eros pellentesque diam,
    sit amet imperdiet est velit eu tellus. Curabitur neque eros, bibendum a augue eget, luctus accumsan turpis.
    Vivamus suscipit, felis sit amet venenatis accumsan, urna purus vestibulum purus, ac porta sapien turpis at massa
    . Phasellus ante purus, fringilla in justo quis, convallis commodo felis. Sed vel ex id lorem egestas faucibus
    eget vitae lorem. Integer faucibus ullamcorper dui, sit amet viverra sapien sodales vel. Nulla ante nibh,
    vulputate a gravida vel, semper vel nisi. Nam quis ligula vulputate, elementum libero eu, feugiat massa.
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam in tincidunt
    enim, non euismod dui.
  </p>
</div>
<div>
  <strong><a name="waluta4">waluta4</a> </strong>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed interdum sapien. Lorem ipsum dolor sit
    amet, consectetur adipiscing elit. Curabitur consequat, leo in sodales sollicitudin, sem eros pellentesque diam,
    sit amet imperdiet est velit eu tellus. Curabitur neque eros, bibendum a augue eget, luctus accumsan turpis.
    Vivamus suscipit, felis sit amet venenatis accumsan, urna purus vestibulum purus, ac porta sapien turpis at massa
    . Phasellus ante purus, fringilla in justo quis, convallis commodo felis. Sed vel ex id lorem egestas faucibus
    eget vitae lorem. Integer faucibus ullamcorper dui, sit amet viverra sapien sodales vel. Nulla ante nibh,
    vulputate a gravida vel, semper vel nisi. Nam quis ligula vulputate, elementum libero eu, feugiat massa.
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam in tincidunt
    enim, non euismod dui.
  </p>
  <a id="toTop" href="#">Go to Top</a>
</div>


</tbody>