japan/config/routes.rb
Rails.application.routes.draw do
  get 'tag/show'

  get 'static_pages/home'

  get 'static_pages/tips'

  get 'search', to: 'search#search'

  resources :attractions

  resources :categories

  resources :regions

  resources :attractions do
    collection { get :search }
  end

  resources :tag

end

japan/app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]
  before_action :tag_cloud



  def tag_cloud
    @tags = Attraction.tag_counts_on(:tags).order('count desc').limit(20)
  end
  # GET /attractions
  # GET /attractions.json
  def index
   # @attractions = Attraction.all

    #if params[:query].present?
    #  @attractions = Attraction.search(params[:query])
    #else
    #  @attractions = []
    #end

   # @attractions = Attraction.search(params[:search])
    if params[:tag].present?
      @attractions = Attraction.tagged_with(params[:tag])
    else
     puts 'nic'# @attractions = Attraction.all.order("created_at DESC")
    end

  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
   # @attraction = Attraction.find(params[:id])
   # @hash = Gmaps4rails.build_markers(@attractions) do |attraction, marker|
   #   marker.lat attraction.latitude
   #   marker.lng attraction.longitude
   # end
    @hash = Gmaps4rails.build_markers(@attractions) do |attraction, marker|
      marker.lat attraction.latitude
      marker.lng attraction.longitude
      marker.infowindow attraction.name
      marker.picture({
                         "url" => "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
                         "width" => 32,
                         "height" => 32
                     })
    end

  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
  end

  # GET /attractions/1/edit
  def edit
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attraction = Attraction.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Attraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.require(:attraction).permit(:tag_list, :tag, :name, :description, :address, :opening_hour, :duration,
                                           :reservation, :more_info, :picture, :url, :latitude, :longitude)
    end
end

japan/app/helpers/attractions_helper.rb
module AttractionsHelper
  include ActsAsTaggableOn::TagsHelper

end

japan/app/views/attractions/_form.html.erb
<%= form_for(@attraction) do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :opening_hour %><br>
    <%= f.text_field :opening_hour %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :reservation %><br>
    <%= f.text_field :reservation %>
  </div>
  <div class="field">
    <%= f.label :more_info %><br>
    <%= f.text_area :more_info %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_area :picture %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>

    <div class="field">
      <%= f.label :tag_list, "Tags (separated by commas)" %><br />
      <%= f.text_field :tag_list %>
    </div>
    <div class="field">
      <%= f.label :latitude %><br>
      <%= f.text_area :latitude %>
    </div>
    <div class="field">
      <%= f.label :longitude %><br>
      <%= f.text_area :longitude %>
    </div>
    <div class="field">

      <%= f.label :name, "Region" %><br />
      <%= f.collection_select :region_id, Region.all,:id,:name, prompt: true %>
    </div>
    <div class="field">

      <%= f.label :name, "Kategoria" %><br />
      <%= collection_select :attraction, :category_id, Category.all,:id,:name, prompt: true %>

    </div>



    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

japan/app/views/attractions/edit.html.erb
<h1>Editing Attraction</h1>

<%= render 'form' %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

japan/app/views/attractions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attractions</h1>

<table>
  <thead>
    <tr>

      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th>Opening hour</th>
      <th>Duration</th>
      <th>Reservation</th>
      <th>More info</th>
      <th>Picture</th>
      <th>Url</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attractions.each do |attraction| %>
      <tr>

        <td><%= attraction.name %></td>
        <td><%= attraction.description %></td>
        <td><%= attraction.address %></td>
        <td><%= attraction.opening_hour %></td>
        <td><%= attraction.duration %></td>
        <td><%= attraction.reservation %></td>
        <td><%= attraction.more_info %></td>
        <td><%= attraction.picture %></td>
        <td><%= attraction.url %></td>
        <td><% attraction.tags.each do |tag| %>
              <%= link_to tag, tag_path(tag) %>
          <% end %></td>
        <td><%= link_to 'Show', attraction %></td>
        <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
        <td><%= link_to 'Destroy', attraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

    <% end %>




  </tbody>
</table>

<br>

<%= link_to 'New Attraction', new_attraction_path %>

japan/app/views/attractions/new.html.erb
<h1>New Attraction</h1>

<%= render 'form' %>

<%= link_to 'Back', attractions_path %>

japan/app/views/attractions/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type='text/javascript'></script>
<p id="notice"><%= notice %></p>





<p>
  <strong>Name:</strong>
  <%= @attraction.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @attraction.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @attraction.address %>
</p>

<p>
  <strong>Opening hour:</strong>
  <%= @attraction.opening_hour %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @attraction.duration %>
</p>

<p>
  <strong>Reservation:</strong>
  <%= @attraction.reservation %>
</p>

<p>
  <strong>More info:</strong>
  <%= @attraction.more_info %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @attraction.picture %>
</p>

<p>
  <strong>Url:</strong>
  <%= @attraction.url %>
</p>
<p>
  <strong>Tag:</strong>
<td><% @attraction.tags.each do |tag| %>
      <%= link_to tag, tag_path(tag) %>
  <% end %></td>
</p>

<p>
  <strong>Szer geo:</strong>

<%= @attraction.latitude %>
</p>
<p>
  <strong>Dł geo:</strong>
<%= @attraction.longitude %>
</p>
<div >
  <div id="multi_markers" style='width: 300px; height: 400px;'></div>
</div>


<script type="text/javascript">
    var szer = <%= @attraction.latitude %>;
    var dlu = <%= @attraction.longitude %>;
    var naz = '<%= @attraction.address %>';

    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: {id: 'multi_markers'}}, function(){
        var markers = handler.addMarkers([
            {

                lat: szer, lng: dlu,
                infowindow: '$naz'.replace('$naz', naz)


            }
        ]);



        handler.bounds.extendWith(markers);

        handler.fitMapToBounds();

    });
</script>



<%= link_to 'Edit', edit_attraction_path(@attraction) %> |
<%= link_to 'Back', attractions_path %>